### ISSUE TITLE
WebPack 2

### ISSUE THREAD

**Issue by MeirionHughes** [w3tecch/aurelia-template-lint-loader#2]
Can't seem to get this to work with WebPack 2. Any chance you could take a look when convenient, please? 

Looks like @niieani has done some extra work too:  https://github.com/niieani/aurelia-template-lint-webpack-loader not sure if this can be pulled and tried?

**Comment by niieani** [comment]
My fork adds options, fixes a couple of things, updates your dependency and converts to TypeScript. Not sure if all of this is something @w3tecch would want, hence my fork.
